name: "docker-redmine"
version: 3.3.1-2
gitUrl: "https://api.github.com/repos/devopskube/docker-mysql/tags"
imageName: "devopskube/redmine"
issueProjectName: "foo"
codeReview: true
chatRoom: "devopskube"
