name: "docker-redmine"
version: 3.4.2-2
gitUrl: "https://api.github.com/repos/devopskube/docker-redmine/tags"
imageName: "devopskube/redmine"
issueProjectName: "foo"
codeReview: true
chatRoom: "devopskube"
